name: Monthly test

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Don't forget to update `Cargo.toml`
      - name: Setup rust 1.84.0
        run: rustup toolchain install 1.84.0 --profile minimal --no-self-update
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --verbose
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c # v1
